-- DDL LANGUAGE COMMANDS --
CREATE DATABASE LEARNING;
CREATE TABLE DDL(
DDL_1 CHAR(20),
DDL_2 INT(20)
);
INSERT INTO DDL 
VALUES('FIRST', 1000, 4);

ALTER TABLE DDL
ALTER COLUMN DDL_1 VARCHAR(20); 

ALTER TABLE DDL
ADD COLUMN DDL_3 BOOLEAN;

ALTER TABLE DDL
drop column DDL_3;

TRUNCATE TABLE  DDL;

DROP TABLE DDL;

-- DML COMMANDS --
INSERT INTO DDL
VALUES ('SECOND', 2000, 1);

INSERT INTO DDL (DDL_1, DDL_2)
VALUES ('SECOND', 2000)